# QT Keys
KEY_DATE = 'date'
KEY_LIVING_LIFE_DATA = 'QuietTimeData'
KEY_LIVING_LIFE_COMM = 'QuietTimeCommentary'
KEY_DAILY_BIBLE_DATA = 'QuietTimeData'
KEY_USER_KEY = 'user_key'
KEY_USER_INFO = 'user_info'
KEY_USER_ADMISSION = 'user_admission'
KEY_USER_ADMIN = 'user_admin'
